import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} md:px-16 px-2 bg-back`}>
        <nav className="flex items-center justify-around py-4">
          <Link href="/" className="text-2xl font-bold text-[#dc2626]">
            tubechapters
          </Link>
          <div className="flex gap-x-8 items-center">
            <Link href="/" className="text-primary text-base font-normal">
              Help
            </Link>
            <Link href="/" className="text-primary text-base font-normal">
              About
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
