import { Jacques_Francois } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const jacques_Francois = Jacques_Francois({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jacques_Francois.className} md:px-16 px-2 bg-back`}>
        <Nav />
        <div className="min-h-[80vh] flex flex-col justify-center items-center relative ">
          {children}
        </div>
        <div
          id="about"
          className="flex flex-col sm:p-8 p-4 text-center gap-y-4 items-center"
        >
          <h2 className="text-2xl font-bold text-[#dc2626]">About us</h2>
          <p className="text-base text-primary max-w-[600px]">
            Welcome to TubeChapters, the ultimate tool for enhancing your
            YouTube experience! We empower you to create captions and timestamps
            for YouTube videos with ease. Our user-friendly interface makes it
            simple for content creators and viewers alike to make videos more
            accessible and navigable. With TubeChapters, you can jump straight
            to the highlights of a video in no time. Join us and revolutionize
            the way you watch YouTube!
          </p>
        </div>
      </body>
    </html>
  );
}
